### ISSUE TITLE
Fetching database property but receiving an excess of redundant information

### ISSUE THREAD

**Issue by siyingloh** [siyingloh/Durrows#3]
Hi, good morning @AaronLeoCooper

I have set up a test page to run an updated profile setting where user will have setup their profile firsthand in Typeform, this information would be stored in a separate set of daabase table which I have been trying to fetch to display onto the profile setting page to allow user to edit and update into the database.

Right now I'm having a small issue with getting the information, as I could pull it from the table, but the displayed text was not what I had expected.

In` test.blade.php`
https://github.com/siyingloh/Durrows/blob/448127f271c6aba14611b0d0b5d69b6efc3a425a/test.blade.php#L27-L30

Is where I have set up the retrieval of data and then
https://github.com/siyingloh/Durrows/blob/448127f271c6aba14611b0d0b5d69b6efc3a425a/test.blade.php#L138-L141
Is where I have set an input to prompt the user with the current value stored displayed into it. 
![image](https://user-images.githubusercontent.com/26007451/48101546-5bd29580-e262-11e8-80f2-041dba9a5948.png)

As can tell from the image, what I wanted displayed in the input would be "siying.loh[at]gmail.com" however displayed was "[{"cilent_email":"siying.loh[at]gmail.com"}]"
I'm not sure which part of the code I might have written wrong, as the approach of using 
```
 $userProfile = DB::table('user_profile')
            ->where('cilent_email',Auth::user()->email)
            ->get();
```
And then fetching the data in the input by adding 
```
<input type="text" name="client_e" id="client_e" value="{{$userProfile->cilent_email }}" class="form-control" autocomplete="off" placeholder="Inspiration">
```

Gave an error of an empty object

**Comment by siyingloh** [comment]
Ah I see, It worked to get only the necessary values! Thanks

**Comment by AaronLeoCooper** [comment]
Awesome! :)
